# Generated by Django 4.2.29 on 2026-04-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(blank=True, help_text='原文发布时间', null=True, verbose_name='原始发布时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, help_text='如：新浪财经、36氪', max_length=100, verbose_name='来源名称'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, help_text='原始资讯URL', max_length=500, null=True, verbose_name='原始链接'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, help_text='AI生成的资讯摘要', verbose_name='AI摘要'),
        ),
    ]
