# Generated by Django 6.0.3 on 2026-04-03 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_published_time_article_source_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_top',
            field=models.BooleanField(db_index=True, default=False, verbose_name='置顶'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], db_index=True, default='draft', max_length=10, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-is_top', '-created_at'], name='blog_articl_is_top_a1ec3d_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-created_at'], name='blog_articl_status_39d3b9_idx'),
        ),
    ]
